[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
token_22_staking = "Dew7MkBAqFZGNnS2sy5JwqBRbiiPPj6gU6MKCi6kLtXm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/tavanam/new-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
