[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
token_22_staking = "DV1Y8ojkz4FsfGEuVAUWYYEViJHRSmLCaTjBArZVP96K"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/tavanam/new-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
